# Netease Music Cookie rewrite resource for Quantumult X
# Add this file as a Rewrite resource.

hostname = interface*.music.163.com

^https:\/\/interface\d?\.music\.163\.com\/eapi\/song\/type\/detail\/get url script-request-header https://raw.githubusercontent.com/xiaozei0707/proxy/refs/heads/main/qx/wangyiyun.cookie.js
