let obj = {
  "subscriptionFeatures": ["NO_NETWORK_ADS","UNLIMITED_HEARTS","LEGENDARY_LEVEL","MISTAKES_INBOX","MASTERY_QUIZ","NO_SUPER_PROMOS","LICENSED_SONGS","CHAT_TUTORS","VIDEO_CALL_IN_PATH","VIDEO_CALL_IN_PRACTICE_HUB","CAN_ADD_SECONDARY_MEMBERS"],
  "purchasableFeatures": ["CAN_PURCHASE_IAP", "CAN_PURCHASE_SUBSCRIPTION"]
};

$done({ body: JSON.stringify(obj), status: 200 });
